package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

func runEnvToYAML(args []string, stdout, stderr io.Writer) error {
	input, output, err := parseIO(args)
	if err != nil {
		return err
	}

	f, err := os.Open(input)
	if err != nil {
		return fmt.Errorf("open %s: %w", input, err)
	}
	defer func() { _ = f.Close() }()

	doc := map[string]any{}
	warnings := []string{}

	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eq := strings.Index(line, "=")
		if eq < 0 {
			warnings = append(warnings, fmt.Sprintf("line %d: missing '=', skipping", lineNum))
			continue
		}
		key := strings.TrimSpace(line[:eq])
		value := line[eq+1:]
		value = stripEnvQuotes(value)

		spec, ok := specByEnvKey(key)
		if !ok {
			warnings = append(warnings, fmt.Sprintf("line %d: unknown env key %s, skipping", lineNum, key))
			continue
		}

		typed, err := coerceEnvValue(value, spec.kind)
		if err != nil {
			warnings = append(warnings, fmt.Sprintf("line %d: %s: %v, keeping as string", lineNum, key, err))
			typed = value
		}

		setYAMLPath(doc, spec.yamlPath, typed)
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("scan %s: %w", input, err)
	}

	for _, w := range warnings {
		_, _ = fmt.Fprintf(stderr, "jay-config: warning: %s\n", w)
	}

	out, closer, err := openOutput(output, stdout)
	if err != nil {
		return err
	}
	defer func() { _ = closer() }()

	bw := bufio.NewWriter(out)
	if _, err := fmt.Fprintf(bw, "# Generated by jay-config env-to-yaml from %s\n", input); err != nil {
		return err
	}
	enc := yaml.NewEncoder(bw)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		_ = enc.Close()
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}
	return bw.Flush()
}

func stripEnvQuotes(v string) string {
	if len(v) >= 2 {
		if (v[0] == '"' && v[len(v)-1] == '"') || (v[0] == '\'' && v[len(v)-1] == '\'') {
			return v[1 : len(v)-1]
		}
	}
	return v
}

func coerceEnvValue(v string, kind fieldType) (any, error) {
	if containsInterpolation(v) {
		return v, nil
	}
	switch kind {
	case typeString:
		return v, nil
	case typeBool:
		switch strings.ToLower(v) {
		case "true", "1", "yes", "on":
			return true, nil
		case "false", "0", "no", "off", "":
			return false, nil
		}
		return nil, fmt.Errorf("not a bool: %q", v)
	case typeInt:
		if v == "" {
			return 0, nil
		}
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("not an int: %q", v)
		}
		return n, nil
	case typeFloat:
		if v == "" {
			return 0.0, nil
		}
		f, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return nil, fmt.Errorf("not a float: %q", v)
		}
		return f, nil
	}
	return v, nil
}

func containsInterpolation(v string) bool {
	return strings.Contains(v, "${")
}

func setYAMLPath(doc map[string]any, path []string, value any) {
	cur := doc
	for i, p := range path {
		if i == len(path)-1 {
			cur[p] = value
			return
		}
		next, ok := cur[p].(map[string]any)
		if !ok {
			next = map[string]any{}
			cur[p] = next
		}
		cur = next
	}
}
