package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

func runYAMLToEnv(args []string, stdout, stderr io.Writer) error {
	input, output, err := parseIO(args)
	if err != nil {
		return err
	}

	raw, err := os.ReadFile(input)
	if err != nil {
		return fmt.Errorf("read %s: %w", input, err)
	}

	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("parse YAML %s: %w", input, err)
	}

	lines, warnings := yamlToEnvLines(doc, input)

	for _, w := range warnings {
		fmt.Fprintf(stderr, "jay-config: warning: %s\n", w)
	}

	out, closer, err := openOutput(output, stdout)
	if err != nil {
		return err
	}
	defer func() { _ = closer() }()

	bw := bufio.NewWriter(out)
	for _, l := range lines {
		if _, err := bw.WriteString(l + "\n"); err != nil {
			return err
		}
	}
	return bw.Flush()
}

func yamlToEnvLines(doc map[string]any, srcPath string) ([]string, []string) {
	lines := []string{fmt.Sprintf("# Generated by jay-config yaml-to-env from %s", srcPath)}
	warnings := []string{}

	for _, spec := range fieldSpecs {
		value, ok := lookupYAMLPath(doc, spec.yamlPath)
		if !ok {
			continue
		}
		lines = append(lines, fmt.Sprintf("%s=%s", spec.envKey, formatEnvValue(value, spec.kind)))
	}

	for key, value := range doc {
		if !topLevelKnownKeys[key] {
			warnings = append(warnings, fmt.Sprintf("skipping unknown YAML key: %s", key))
			continue
		}
		if key == "scrub" {
			if m, ok := asMap(value); ok {
				for sk := range m {
					if !scrubKnownKeys[sk] {
						warnings = append(warnings, fmt.Sprintf("skipping unknown YAML key: scrub.%s", sk))
					}
				}
			}
		}
		if key == "seed_token" {
			if m, ok := asMap(value); ok {
				for sk := range m {
					if !seedTokenKnownKeys[sk] {
						warnings = append(warnings, fmt.Sprintf("skipping unknown YAML key: seed_token.%s", sk))
					}
				}
			}
		}
	}

	return lines, warnings
}

func lookupYAMLPath(doc map[string]any, path []string) (any, bool) {
	var cur any = doc
	for _, p := range path {
		m, ok := asMap(cur)
		if !ok {
			return nil, false
		}
		v, present := m[p]
		if !present {
			return nil, false
		}
		cur = v
	}
	return cur, true
}

func asMap(v any) (map[string]any, bool) {
	switch m := v.(type) {
	case map[string]any:
		return m, true
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			ks, ok := k.(string)
			if !ok {
				return nil, false
			}
			out[ks] = val
		}
		return out, true
	}
	return nil, false
}

func formatEnvValue(v any, kind fieldType) string {
	if v == nil {
		return ""
	}

	switch kind {
	case typeBool:
		if b, ok := v.(bool); ok {
			if b {
				return "true"
			}
			return "false"
		}
		return strings.ToLower(fmt.Sprint(v))
	case typeInt, typeFloat:
		return fmt.Sprint(v)
	case typeString:
		s, ok := v.(string)
		if !ok {
			s = fmt.Sprint(v)
		}
		return quoteEnvString(s)
	}
	return fmt.Sprint(v)
}

func quoteEnvString(s string) string {
	if s == "" {
		return ""
	}
	if strings.HasPrefix(s, "${") && strings.HasSuffix(s, "}") && !strings.ContainsAny(s[2:len(s)-1], " \t\"\\") {
		return s
	}
	if needsQuoting(s) {
		return `"` + escapeDoubleQuoted(s) + `"`
	}
	return s
}

func needsQuoting(s string) bool {
	for _, r := range s {
		if r == ' ' || r == '\t' || r == '"' || r == '\'' || r == '\\' || r == '#' || r == '\n' {
			return true
		}
	}
	return false
}

func escapeDoubleQuoted(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
